### ISSUE TITLE
Question: What is the equivalent function of Numpy zero in Scidart?

### ISSUE THREAD

**Issue by remcova** [scidart/scidart#10]
I want to create a multidimensional array filled with zeros based on a given shape. I found the zeros function in Scidart but it can only create one dimensional arrays right?

**Comment by angelopolotto** [comment]
Yes, Zeros only support one dimension. I could not fount at time a generic way solver dimensions problem, so, I first developed for one dimension. But that problem is easy to solve with the following code:

```dart
import 'package:scidart/numdart.dart';

var mA = Array2d.empty();
var line = zeros(3);
mA.add(line);
mA.add(line);
mA.add(line);

print(mA); // 3x3 matrix of zeros
```

I hope that can solve your problem for now, otherwise, we can create a other function and update the SciDart.

Regards!

**Comment by remcova** [comment]
Thank you for the fast reply :)
What is the best way to create a dynamic function for this? because I need this functionality for image processing so the shapes are different each time.

**Comment by remcova** [comment]
Never mind, I found my solution. I didn't solve it with Scidart but Scidart is for sure useful. Thanks.

**Comment by angelopolotto** [comment]
The main problem with SciDart and Dart language em general, is change the dimension number for example: Change make a Matrix with 2 dimensions to N dimensions, that N always need be specified e can't be a generic number.
For your case, is a 3 dimensions matrix with variable number of elements in each dimension, as you said, 736x736x4.
But, unfortunately, SciDart don't have support for 3D matrix and operations yet. But you can share your problem to help SciDart be better.

**Comment by remcova** [comment]
Will definitely share my ideas on it when I have the time. I have one more question though, does Scidart have a similar function of np.stack?

**Comment by angelopolotto** [comment]
SciDart don't have yet a function generic as np.stack, but It has some array manipulation that can be helpful, see some tests as example:

- https://github.com/scidart/scidart/blob/master/test/numdart/arrays_base/array_operations/array_to_column_matrix_test.dart

- https://github.com/scidart/scidart/blob/master/test/numdart/arrays_base/array_operations/array_reshape_to_matrix_test.dart

- https://github.com/scidart/scidart/blob/master/test/numdart/arrays_base/array2d_test.dart
