### ISSUE TITLE
PolyFit is not working as reqired

### ISSUE THREAD

**Issue by HarshitSingh1509** [scidart/scidart#16]
I was performing PolyFit(x, y, 3) but the equation which I got after this is of order 8. My x and y array are of length 9. Please help me.

**Comment by polotto** [comment]
Hello. What is your expected results? Can you share all the values that you used?

**Comment by HarshitSingh1509** [comment]
[0.01, 0.012],
        [0.02, 0.024],
        [0.03, 0.040],
        [0.04, 0.050],
        [0.05, 0.062],
        [0.06, 0.075],
        [0.07, 0.091],
        [0.08, 0.099],
        [0.09, 0.115]
these are the x and y values. after PolyFit(x,y,3). I was expecting a 3 degree polynomial but I am getting something like this  37450396823.87154 x^8 +  -14811507935.892578 x^7 +  2471180555.4509788 x^6 +  -226305555.54582798 
x^5 +  12373211.80501761 x^4 +  -410070.1388709476 x^3 +  7937.929563144283 x^2 +  -79.11511904410882 x +  0.315999999986331   (R^2 = -5539833555322.959).
my code is something like
List<double> x = [];
    List<double> y = [];
    for (int i = 0; i < n; i++) {
      x.add(ar[i][0]);
      y.add(ar[i][1]);}
    var xf = Array(x);
    var yf = Array(y);
    const int s = 3;
    var eq = PolyFit(xf, yf, s); 
print(eq);
and the result I have shown above that is 8 degree polynomial
Thankyou for such an amazing package

**Comment by polotto** [comment]
I got it. I need time to analyse the problem, maybe this can be a fault in the polyfit algorithm, all that statical approximation it's really hard to implement and debug.
It's really great see someone enjoying the package, if possible, tell me more about what you doing. A show case of SciDart is amazing think to put in your official website.

**Comment by HarshitSingh1509** [comment]
I am working on a college project, which is going to be applied on industrial practices of absorbing columns. Actually this project is based on the application of graphical techniques like plotting graph of the data and doing calculation on the curve. I want to make a 3 degree polynomial equation, Kindly help me for this project and I am very grateful that you are helping me.

**Comment by polotto** [comment]
I fixed the PolyFit degree problem, please, update to version scidart 0.0.1-dev.9
