### ISSUE TITLE
matrixTranspose ist not working as intended 

### ISSUE THREAD

**Issue by ToluAta** [scidart/scidart#18]
Hi, 

the ```matrixTranspose``` function is faulty for matrices with dimmensions m != n.  
I would like to propose to switch the places of ```a.column``` and ```a.row``` in line 19.

**Comment by polotto** [comment]
That is a corner case, definitely. Thank you to find that. Can you share you matrix values? I need them to create new test cases.

**Comment by ToluAta** [comment]
Yes of course.
The values have been tested in NumPy. So following should be the output:
/// var a = Array2d([
///  >>>  Array([1.0, 2.0, 3.0]),
///  >>>  Array([3.0, 2.0, 1.0]),
///  ]);
///  >>> matrixTranspose(a);
///  Array2d([
///    Array([1.0, 3.0]),
///    Array([2.0, 2.0]),
///    Array([3.0, 1.0])
///  ]);

**Comment by polotto** [comment]
I solved that issue and improved SciDart doc, please, update to 0.0.1-dev.10.

Thank you!
