### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by debuggerx01** [scidart/scidart#24]
Thanks for the great package!

Do you plan to make a null safe update of the package?

**Comment by polotto** [comment]
I've been waiting to stable release of null safe in Dart. Now, seems to be stable, I plan to migrate soon.

**Comment by debuggerx01** [comment]
Any update :question:

**Comment by polotto** [comment]
Unfortunately, my time is very short and I'm alone in the project, please, to implement, if you want to, or wait for my update.

**Comment by polotto** [comment]
Please, update to the version 0.0.2-dev.1 , this version is null safe!
