### ISSUE TITLE
Question: What's the equivalent of indexing of numpy  

### ISSUE THREAD

**Issue by bibs2091** [scidart/scidart#30]
Hello,
what is the equivalent of indexing only row/columns in :
`array[ : , i ]`
or 
`array[ 1:5 , i  ]`
in numdart, i want to get only one row/colum values but

**Comment by polotto** [comment]
Unfortunately, Dart can't have this pythonic indexing but I did some methods to make your life more easy:

```dart
var matrix = Array2d.empty();
var line = Array([1.0, 2.0, 3.0, 4.0, 5.0]);

matrix.add(line);
matrix.add(line);
matrix.add(line);

print(matrix.getColumn(1));
print(matrix.subArray2d(1, 5, 2, 2));
```

Please, update to version: 0.0.2-dev.5 .
