### ISSUE TITLE
Array2d.fromArray is not deep copying the arrays in the list of arrays

### ISSUE THREAD

**Issue by bjornwilliam** [scidart/scidart#31]
Example:
`     var Mcat = nd.Array2d([
      nd.Array([0.8951, 0.2664, -0.1614]),
      nd.Array([-0.7502, 1.7135, 0.0367]),
      nd.Array([0.0389, -0.0685, 1.0296]),
    ]);  
 var mcatCopy = Mcat.copy();
   mcatCopy[0][0] = 0.5;  `

Now Mcat[0][0] is also equal to 0.5 

The problem seems to be that 
`   Array2d.fromArray(Array2d list) {
    // deep copy of the parameter
    l = list.map((element) => element).toList();
  }
 `
just shallow copies the arrays stored in the list of arrays for Array2d.

Fix:
`  
Array2d.fromArray(Array2d list) { 
// deep copy of the parameter  
    l = list.map((element) =>  Array.fromArray(element)).toList();  
  }
`

**Comment by polotto** [comment]
Thank you to find and solve this problem. I'll try publish this update soon.

**Comment by polotto** [comment]
Please, update to version: 0.0.2-dev.5 .
