### ISSUE TITLE
Typos in the Source Code

### ISSUE THREAD

**Issue by mishkov** [scidart/scidart#35]
Hello there 👋

I think I found the typo in the rfft documentation:
https://github.com/scidart/scidart/blob/201ca580ec21251318119360f43a73e28808419e/lib/src/scidart/fftpack/rfft/rfft.dart#L5
Please correct me if I am wrong. But if it is typo, can I create a pull request to fix it?

One more typo in the fft.dart comment:
https://github.com/scidart/scidart/blob/f14905035157331f387af1c98272a7524cf525d5/lib/src/scidart/fftpack/fft/fft.dart#L74
As I know there is no "cooley turkey algorithm" 🙂

**Comment by polotto** [comment]
Hello there

Will you do a PR to fix these typos? I need to close this issue.

**Comment by mishkov** [comment]
Fixed typos is merged

**Comment by polotto** [comment]
Update to 0.0.2-dev.7 to get your PR.
