### ISSUE TITLE
The name of arange()

### ISSUE THREAD

**Issue by mishkov** [scidart/scidart#39]
At the moment we have the [arange()](https://github.com/scidart/scidart/blob/201ca580ec21251318119360f43a73e28808419e/lib/src/numdart/spaces/arange.dart#L36) method with a name from [python repo](https://github.com/numpy/numpy/blob/7125cdfa21081b91907a65b6c888791cf150a0b2/numpy/array_api/_creation_functions.py#L75-L94), if I am right. The problem is that the name of arange() method does not match [Dart name conventions](https://dart.dev/guides/language/effective-dart) because it contains some abbreviation which is [bad practice](https://dart.dev/guides/language/effective-dart/design#avoid-abbreviations). The name [as described here](https://github.com/numpy/numpy/issues/20192#issuecomment-951237045) means "array range" and should have other name. It can be `createArrayRange`, `buildArrayRange`, or less readable `arrayRange`.

P. S.
Maybe I am paranoiac or crazy clean coder but I would like to get your opinion about that.

**Comment by polotto** [comment]
I really don't care much about how to name things, I always try put something that make sense in the context. But I agree with you, that name `arange` definitely is not the best, my intention was approximate SciDart with SciPy naming. At the end, I don't know if worth change the name because this will be a broken change just for stylist proposes.

**Comment by mishkov** [comment]
> this will be a broken change

No, I don't think so. We can annotate current method as `@deprecated` and just add new method which will just call old method. And in future we will remove all method and replace body of new method with old.

**Comment by polotto** [comment]
That's right! Do you want proceed the PR to make this changes? I liked the name `createArrayRange`.

**Comment by mishkov** [comment]
Ok! It will be done!

**Comment by polotto** [comment]
Great!!! @mishkov thank you for the contributions! Do you miss some function/method/functionality in library yet? I would like to hear you option about it. That will help me decide what implement for the next versions.

**Comment by polotto** [comment]
Please, update to version: `scidart: ^0.0.2-dev.9` to get your PR.
