### ISSUE TITLE
Plans to implement a function to extract MFCCs

### ISSUE THREAD

**Issue by certainlyWrong** [scidart/scidart#45]
Scidart is truly an amazing initiative, and it could get even more amazing. Are there plans to implement a function to extract MFCCs?

**Comment by polotto** [comment]
Not yet, I'm planning to expand some stuff in October.

**Comment by certainlyWrong** [comment]
Great job. Some really cool projects came up in that time. See this [implementation](https://github.com/liamappelbe/fftea).

Through it develops a [function](https://github.com/certainlyWrong/mfcc_bee) for extracting MFCCs, it still needs to be refactored a lot.

**Comment by polotto** [comment]
Can I incorporate this idea in Scidar?

**Comment by certainlyWrong** [comment]
> Posso incorporar essa ideia no SciDart?

Of course I do, I want SciDart to be very powerful.

**Comment by polotto** [comment]
Do you wish do the job, or Do you want that I do it?

**Comment by certainlyWrong** [comment]
> Do you wish do the job, or Do you want that I do it?

48 days to go until my vacation. For the time being I cannot devote myself entirely to this. Soon, you will have to start. Anyway, even though I'm new to this programming universe, I can try to help you. I can also tell you that the results of this implementation are satisfactory. I got 91 accuracy in some tests.

**Comment by polotto** [comment]
just provide the expected inputs and outputs for me. This will help a lot my work.

**Comment by polotto** [comment]
No problem! Once I understand the results, I'll replace the test data.
