### ISSUE TITLE
Benchmarks for common functions.

### ISSUE THREAD

**Issue by Piero512** [scidart/scidart#51]
Hi

I would like to see benchmarks for commonly needed fast math, like FFTs and such.

I would also consider bundling a BLAS library for the main platforms through flutter/ ffi

**Comment by polotto** [comment]
unfortunately, the benchmarks is hard to do because they change for each platform, this is why I decided focus in other stuff, since I've been keeping the library by myself. About the native implementations,  they are out of the main scope of the project: scientific multi platform library.
